import { Geist, Geist_Mono, Inter } from "next/font/google";
import "../globals.css";
import Navbar from "@/app/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
////////////

// TODO fix this (can't have html or body here. It's already in the app layout)
export default function AdminLayout({ children }) {
  return (
    <html lang="en">
      <head>{/* <script src="https://cdn.tailwindcss.com"></script> */}</head>
      <body className={`${inter.className} antialiased`}>{children}</body>
    </html>
  );
}
